kpatch-build: fix for new .cmd file format in 5.19 kernels
$(dot-target).cmd in 5.19 kernel now has basename for those .o files,
i.e., array.o (in 5.19) instead of fs/proc/array.o (in 5.18). This causes
kpatch-build error as:

 ERROR: invalid ancestor fs/proc/array.o for fs/proc/array.o.

Fix this by grepping for both $grepname and $file.

Signed-off-by: Song Liu <song@kernel.org>